### PR TITLE
Make MaximumTrainer compile on MacOS again

### PR DESCRIPTION
**Pull request by mkazia**
With the current state of code, it is not compiling MacOSX. With these changes, I'm able to compile on MacOSX.

### CODE REVIEW

**Review by MaximumTrainer — APPROVED** [review]
Thanks. Post compile did this run ok on your local instance? 
Do feel free to provide additional contributions.

Thanks

**Comment by mkazia** [comment]
After compiling, I run this command `install_name_tool -add_rpath /usr/local/lib build/release/MaximumTrainer.app/Contents/MacOS/MaximumTrainer`, the app is able to launch but it is trying to connect to maximumtrainer.com and times out.
Is there the server part I can run on local machine or is there a way to launch the app without having to connect to the server?

**Comment by MaximumTrainer** [comment]
Can you please raise an issue on this?
This code was donated to open source when the domain expired & im now picking this up to revive.
As such the maximum trainer domain doesn't exist & I suggest commenting out the code that performs the remote connection.
Imho I don't see any reason it's needed, although I would like to update this to use ergdb/trainer day directly via their api.

**Comment by oldnapalm** [comment]
It would be nice to have this working without the login. I think the server was used also to store workouts and power curves (for virtual power from speed sensor). I would be glad to contribute with some workouts and power curves.

**Comment by mkazia** [comment]
Looks like issues are not enabled on the project repo.
From cursory glance at the code it looks like the initial connection is to check if there is a new version of the app available, after that it looks like it is attempting to perform a user login and pulls some user data after successful login.

**Comment by MaximumTrainer** [comment]
> It would be nice to have this working without the login. I think the server was used also to store workouts and power curves (for virtual power from speed sensor). I would be glad to contribute with some workouts and power curves.

My goal with this is to integrate with ergdb/trainerday for workouts via their api, but would be very happy for you to contribute to this if you like.

**Pull request merged**
